#!/bin/sh

bash ./schema-uninstall

rm "/usr/local/bin/learntotouchtype"
rm "/usr/share/icons/hicolor/16x16/apps/learntotouchtype.png"
rm "/usr/share/icons/hicolor/48x48/apps/learntotouchtype.png"
rm "/usr/share/icons/hicolor/scalable/apps/learntotouchtype.svg"

# NB: user-specific  ~/.local/share/applications has been a flop for me
rm "/usr/share/applications/uk.co.archaicgroves.learntotouchtype.desktop"
gtk-update-icon-cache /usr/share/icons/hicolor/
