#!/bin/sh

# NB: unmodified MESON_BUILD_ROOT point to the top directory(?)
bash ./schema-install

cp "${MESON_SOURCE_ROOT}/learn_to_touch_type.py" "/usr/local/bin/learntotouchtype"
cp "${MESON_SOURCE_ROOT}/icons/learntotouchtype16x16.png" "/usr/share/icons/hicolor/16x16/apps/learntotouchtype.png"
cp "${MESON_SOURCE_ROOT}/icons/learntotouchtype48x48.png" "/usr/share/icons/hicolor/48x48/apps/learntotouchtype.png"
cp "${MESON_SOURCE_ROOT}/icons/learntotouchtype.svg" "/usr/share/icons/hicolor/scalable/apps/learntotouchtype.svg"

# NB: user-specific  ~/.local/share/applications has been a flop for me
cp "${MESON_SOURCE_ROOT}/uk.co.archaicgroves.learntotouchtype.desktop" "/usr/share/applications/uk.co.archaicgroves.learntotouchtype.desktop"
gtk-update-icon-cache /usr/share/icons/hicolor/
